apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig-be
spec:
  healthCheck:
    checkIntervalSec: 20
    timeoutSec: 20
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health
