apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: game-health
  namespace: production
spec:
  healthCheck:
    checkIntervalSec: 20
    timeoutSec: 20
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
